### ISSUE TITLE
Agent capability tooltip shows as agent disconnect in overview tab

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#1006]
![UI bug for hover](https://user-images.githubusercontent.com/56211853/215891766-ead015e8-5232-4a2b-9924-f72584e4bd1c.png)

Should relabel this to be "agent capability unhealthy", or something along those lines.

**Comment by codyrancher** [comment]
@alexandreLamarre what's the expectation for the tooltips?

Currently there's 3 TimelineTypes:
- Timeline_Unknown
- Timeline_Alerting
- Timeline_Silenced

What would you like each to show?
