### ISSUE TITLE
Agent Privileged Identities

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#1056]
https://github.com/rancher/opni/blob/main/enhancements/gateway/20230130-distinguishing-central-agent.md

The agent should be able to assert privileged identities by authenticating with temporary keys in its keyring.

**Comment by sanjay920** [comment]
rolling over to next sprint

**Comment by sanjay920** [comment]
https://github.com/rancher/opni/pull/1060

**Comment by kralicky** [comment]
Completed in https://github.com/rancher/opni/pull/1060
