### ISSUE TITLE
Upstream opni agent identification

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#1083]
Related OEP: https://github.com/rancher/opni/blob/main/enhancements/gateway/20230130-distinguishing-central-agent.md

The central agent can be distinguished from other agents using a well-known label in its session attributes list, obtained from the management API

**Comment by sanjay920** [comment]
Still being worked on

**Comment by kralicky** [comment]
Dependent on https://github.com/rancher/opni/pull/1060
Implemented in https://github.com/rancher/opni/pull/1132
