### ISSUE TITLE
[EPIC] implement streaming data-loader for log anomaly detection model training to reduce memory pressure

### ISSUE THREAD

**Issue by tybalex** [rancher/opni#1094]
## Summary: 
 The AIOps log anomaly detection model can train a model using a streaming data-loader, such that it doesn't have to load all training dataset into memory. Instead, it will only dump a subset of training dataset each time and train with that subset of data. This feature significantly reduces the memory resource pressure in the model training service.

 ## Use case: 
 When Opni's user launches a workload log anomaly detection training job with huge size of training data (for example, 500GB logs), the current approach that loads all data into memory won't be feasible. The streaming data-loader can resolve this problem because it only loads a reasonable subset of training dataset each time.

 ## Benefits: 
 * Resolve the memory pressure issue in the scenario that training data size is large.
 

## Level of effort: 
 * Code implementation: <= 2 days. 
 * Testing and debugging: 8 days. This includes testing the features in multiple rounds in a long running cluster, and then to fix any edge cases found in this process.

## Issues
* https://github.com/rancher/opni/issues/1095

**Comment by sanjay920** [comment]
Made it into 0.8.3

**Comment by tybalex** [comment]
Further improvement will be created in a separate OEP.
