### ISSUE TITLE
[BUG] Roles disappear after creation in admin UI

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#1109]
Roles disappeared after some time. 

![image](https://user-images.githubusercontent.com/6551215/221040434-f6b3abda-76f8-46e2-b58e-1053fc9536de.png)

Roles do exist, as seen in the role bindings page:
![image](https://user-images.githubusercontent.com/6551215/221040594-a25f0182-412b-439e-a72a-ce26cb391267.png)

**Comment by codyrancher** [comment]
Resolved in the latest.
