### ISSUE TITLE
[BUG] Deployments in AIOps watchlist disappear

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#1110]
Becomes very inconvenient when an existing watchlist has already been trained

![watchlist_disappear](https://user-images.githubusercontent.com/6551215/221051681-c0711b10-fb85-4a9c-ac1a-5924d56940d3.gif)

**Comment by codyrancher** [comment]
I think the reason the selection is disappearing is because you click on the row instead of the checkbox.

That's how the table works in all of rancher so I don't intend to fix it. You can use ctrl/shift+row click to select multiple.
