### ISSUE TITLE
Move ETL tool to custom plugin

### ISSUE THREAD

**Issue by joshmeranda** [rancher/opni#1118]
To avoid compatibilty issues with installing two `kube-prometheus-stack` instances in the same cluster, we should move the data import tool to its own plugin instead of shipping it as part of the metrics.

**Comment by sanjay920** [comment]
Manual testing has begun. PR to follow

**Comment by joshmeranda** [comment]
Closing in favor of solution described here: https://github.com/rancher/opni/pull/1210
