### ISSUE TITLE
[EPIC] Human Readable Logging Cluster Names

### ISSUE THREAD

**Issue by joshmeranda** [rancher/opni#1126]
## Summary: 
Currently, when users select an agent cluster for log analytics, they select from a list of cluster IDs. This makes it difficult to select the right agent among many. This proposal aims to add human-readable agent cluster names, to help differentiate the cluster names for the user.

In the Opni UI, we will adda a new "Clusters" tab which will be responsible for displaying the available clusters and their metadata to the user.

 ## Use case: 
When an Opni Gateway has many connected agents, it becomes cumbersome to search through a list of IDs to find the one which matches the target agent.

 ## Benefits: 
 By viewing a list of human-readable names, it will be immediately clear which cluster you are selecting. While the IDs do uniquely identify each agent, it's not immediately clear what responsibilities each agent has. Human-readable names will make agent responsibility clearer, as well as being easier to remember.

## Level of effort: 
This addition should take 1.5 weeks for implementation and testing. The aim is to have this up for the March 15th release.

## Issues
* https://github.com/rancher/opni/issues/1057
* https://github.com/rancher/opni/issues/1115
* https://github.com/rancher/opni/issues/1116
* https://github.com/rancher/opni/issues/1117

**Comment by sanjay920** [comment]
On track after sprint 3
