### ISSUE TITLE
Per-tenant Cluster Info Metrics

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#1157]
OEP: https://github.com/rancher/opni/blob/main/enhancements/monitoring/20230131-tenant-impersonation.md
Using the new local agent identification feature, modify the `opni_cluster_info` metric to use tenant impersonation as described in https://github.com/rancher/opni/pull/1013

**Comment by kralicky** [comment]
This can be started on now that https://github.com/rancher/opni/pull/1060 and https://github.com/rancher/opni/pull/1132 are completed.

**Comment by kralicky** [comment]
In order to efficiently intercept remote write payloads, I'm going to update the metrics plugin to use native prometheus write request protobuf types. This should also be mostly reusable for otel metrics format in the future.

**Comment by kralicky** [comment]
For easier testing of the new metrics, I am adding Grafana support to the test env. Tracked in https://github.com/rancher/opni/issues/1227
