### ISSUE TITLE
[BUG] Address situation where model files are removed after training

### ISSUE THREAD

**Issue by AmartC** [rancher/opni#1199]
Sometimes, when it is time to train a new model, the request to clear S3 of any model files is made after the model has been trained instead of before. More investigation will be necessary as to what causes this but a resolution found is to sleep for a few seconds after making the request to clear S3 of old model files before submitting the request to train the latest model.

**Comment by AmartC** [comment]
https://github.com/rancher/opni-inference-service/pull/41 has been merged in which will resolve this but further investigation will be needed.

**Comment by AmartC** [comment]
Investigate approach where model training for new model only begins once S3 has been cleared for the prior model.

**Comment by sanjay920** [comment]
https://github.com/rancher/opni/pull/1222

**Comment by AmartC** [comment]
Rolled over to sprint 5.
