### ISSUE TITLE
Payload Receiver High Memory Usage

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#126]
Payload Receiver appears to be using an unusually high amount of memory (runtime approx. 48 hrs)
![image.png](https://zube.io/files/rancher/fa7f81dbb355571508bab66db79e08aa-image.png)
![image.png](https://zube.io/files/rancher/5df863a94829aa258f05ada4b50bb190-image.png)

**Comment by kralicky** [comment]
Metrics from a long-running opni cluster indicate a possible memory leak (screenshot shows 24 hours of data)
![Screenshot from 2021-11-01 14-03-17.png](https://zube.io/files/rancher/4d2292113957a75fa952a88daed426d3-screenshot-from-2021-11-01-14-03-17.png)

**Comment by kralicky** [comment]
High memory usage in payload receiver is due to logs coming in faster than they can be processed. Logs get backed up and stored in memory until the volume of incoming logs slows enough for the system to catch up, or when the preprocessing service runs out of memory.

**Comment by sanjay920** [comment]
Opni has moved away from payload receiver service
