### ISSUE TITLE
Update nulog inference service ES endpoint

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#13]
https://github.com/rancher/opni/blob/4f3268ea4977f03a5c88b46f3b4df23ea2eda47f/src/nulog-inference-service/nulog-inference-service.yaml#L23

**Comment by tybalex** [comment]
the needed change for this issue is included in this PR #12 .

**Comment by tybalex** [comment]
PR #12 which addresses this issue has been merged, close issue.
