### ISSUE TITLE
Workload Insights page not showing even with logging enabled.

### ISSUE THREAD

**Issue by AmartC** [rancher/opni#1343]
Even after enabling Opni logging, the workload insights page within Opni is not showing and asking for Opni logging to be enabled. 

![Screenshot 2023-04-24 at 4 00 10 PM](https://user-images.githubusercontent.com/8761010/234342366-eab97a24-4632-416b-9933-4aebb93883c7.png)

**Comment by codyrancher** [comment]
https://github.com/rancher/opni-ui/pull/138
