### ISSUE TITLE
Add warning banner when monitoring backend is installed, but local agent doesn't have metrics capability

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#1358]
This warning would be useful because opni internal metrics are scraped by the local agent's prometheus, so if the local agent doesn't have the metrics capability, some features might not be available in the Grafana dashboards.

**Comment by codyrancher** [comment]
@kralicky  I think it would also be helpful to have the banner in the grafana dashboard since that's where the user will likely run into the issue this helps prevent?
