### ISSUE TITLE
Dynamic reload of otel collector

### ISSUE THREAD

**Issue by dbason** [rancher/opni#1426]
With the introduction of metrics the config for Otel collector is much more dynamic.  This means that redeploying a pod on config change is no longer feasible, we should be reloading the config inside the pod.  This will also avoid loops where the otel collector pod itself is also being monitored.

Ideally we should be able to push updated config to Otel collector via http/s, but currently this is not an option; the http configuration is pull only.  Otel collector currently has the option to reload using a SIGHUP but this is _somewhat_ tricky in Kubernetes.  There is an issue to support webhook cofiguration - https://github.com/open-telemetry/opentelemetry-collector/issues/7704

Currently I believe the best approach is to fork https://github.com/jimmidyson/configmap-reload and add support for process SIGHUP reloading.

**Comment by kralicky** [comment]
I think we should just implement a `Provider` interface to watch for changes as documented in https://github.com/open-telemetry/opentelemetry-collector/tree/main/confmap#watching-for-updates
