### ISSUE TITLE
Opni logging should collect traces

### ISSUE THREAD

**Issue by dbason** [rancher/opni#1605]
This will involve:

1. Implementing Export methods for traces in the otel forwarder
2. Adding a trace pipeline to the otel preprocessor config
3. Implementing an Export method for traces in the gateway
4. Adding a trace pipline to the otel config for logging.

**Comment by jaehnri** [comment]
@dbason I have a few questions 😅 

1. I've understood that the logging plugin has a forwarder responsible for sending data to the upstream cluster via OTLP. In the upstream, the component responsible for receiving these OTLP logs is this `supportagent`?

2. Should traces be stored in OpenSearch too?

3. Is the following the preprocessing and OpenSearch ingestion pipeline?
https://github.com/rancher/opni/blob/13d8a9f065c088bf35c4bcbc63b59061405ba3a0/pkg/resources/preprocessor/workloads.go#L93-L98

**Comment by dbason** [comment]
The supportagent is something different, that's a standalone tool.  I'll ping you and we can set up something to go over the artchitecture.

**Comment by jaehnri** [comment]
As of now, there is no support for traces in our custom OpenSearch exporter:
https://github.com/dbason/opentelemetry-collector-contrib/tree/opensearch-exporter/exporter/opensearchexporter

However, there is ongoing development for it (see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23611), and traces, specifically, should be added soon (see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24540).

For that matter, we planned to pause the development of this feature for now and come back when at least the traces are available.
