### ISSUE TITLE
Changing Alerting to HA does not work as expected

### ISSUE THREAD

**Issue by dbason** [rancher/opni#1621]
Not sure if this was actually caused by HA but initially set cluster up as HA then updated to Standalone.  Alerts did not change out of pending mode.

Tried deleted the pvc and recreating the pod but this did not help.  After restarting the gateway the alerts then changed as expected.

**Comment by alexandreLamarre** [comment]
note : this can be a symptom of https://github.com/rancher/opni/issues/1583

For the time being, like you mentioned restarting the gateway should fix this
