### ISSUE TITLE
Otel collector reconciler sometimes not retrying after a timeout error

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#1690]
It appears that we might need to adjust the retry logic here: https://github.com/rancher/opni/blob/a79467444167ef1fa31ee4bf22ca587fd0c2dd67/plugins/metrics/pkg/agent/drivers/opni_manager_otel/otel_driver.go#L95-L130

**Comment by alexandreLamarre** [comment]
https://github.com/rancher/opni/blob/a79467444167ef1fa31ee4bf22ca587fd0c2dd67/plugins/metrics/pkg/agent/drivers/opni_manager_otel/otel_driver.go#L122-L130

It's this reconcile specifically that needs to be adjusted:
```
[31mERROR[0m [36mplugin.metrics.otel[39m [2mopni_manager_otel/otel_driver.go:126[22m error reconciling object {"nodeId": "9d32017b-ec23-4ede-bef6-c727e1fee351", "object": "opni collector", "error": "rpc error: code = Unknown desc = dial tcp: <redacted>: Try again"}
```
