### ISSUE TITLE
Unable to ship Rancher logs to Opni

### ISSUE THREAD

**Issue by barryboubakar** [rancher/opni#172]
Hello,

We are trying Opni in a Rancher2.6.2/RKE1 environment.
The Opni operator and the Opni cluster are deploy using this [procedure](https://opni.io/deployment/basic/).

We have configurde the log shipping using this [procedure ](https://opni.io/setup/log-shipping/ ) but in the Opensearch there is no index.

We also see that the type of the cluster output should be `ElasticSearch` but in the UI we see `Unknown`.

The API used for opni is `logging.opni.io`. We configured the cluster output with the `logging.opni.io` API and we create a second with the `logging.banzaicloud.io` API but both of them are "Unknown".

I attached the log of the pods opni-svc-payload-receiver, opni-controller-manager-manager, opni-controller-manager-kube-rbac-proxy and the rancher-logging-fluentd.

Thank you for your help. 

[opni-controller-manager-manager.log](https://github.com/rancher/opni/files/7915123/opni-controller-manager-manager.log)
[rancher-logging-fluentd.log](https://github.com/rancher/opni/files/7915124/rancher-logging-fluentd.log)
[opni-controller-manager-kube-rbac-proxy.log](https://github.com/rancher/opni/files/7915125/opni-controller-manager-kube-rbac-proxy.log)
[payload-receiver.log](https://github.com/rancher/opni/files/7915126/payload-receiver.log)

**Comment by dbason** [comment]
Hi @barryboubakar thanks for the logs.  I've found a bug in the code that is stopping the reconciliation loop, but I don't believe this is causing the issue.  To remove the errors in the log you can remove the following lines from your opnicluster resource:
```
      prometheus:
        name: prometheus-name #The name of the prometheus resource
        namespace: prometheus-namespace #The namespace the prometheus resource is in
```

Are you currently using rancher-logging?  If so you shouldn't create any resources under the `logging.opni.io` api as these could conflict with resources created by the `logging.banzaicloud.io` API.  If you're not using rancher-logging you can just use the logadapter resource to create everything required.

The fluentd errors indicate that there is an SSL error connecting to the payload-receiver service.  For intracluster communication there isn't any SSL setup for the payload receiver so it should just be on http in your cluster output.  Could you attach the cluster output you are using?  Also does your cluster have a service mesh at all?

**Comment by barryboubakar** [comment]
Hello, 

Thank you for your reply. As you suggested, we removed the prometheus lines in opnicluster resource.

We are currently using Rancher Logging and to avoid any conflict we removed the ClusterOutput that was using the API `logging.opni.io`. We solved our Fluentd issue by increasing the livenessProbe timeout to 60s (default 30s). Now the fluentd container is running properly. 

After redeploying the opni cluster, we now see an index named `logs` in the opensearch.  Is this the index we need to expect ? 

Find below the ClusterOutput and for information we are not using any serviceMesh. 

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: opni-es-co
  namespace: cattle-logging-system
spec:
  http:
    buffer:
      chunk_limit_size: 1mb
      flush_interval: 2s
      tags: '[]'
      timekey: ""
    content_type: application/json
    endpoint: http://10.43.32.232:
    json_array: true 
```

Thank you.

**Comment by dbason** [comment]
The logs index should be an alias.  If everything is work as expected it should reindex anything in that into a `logs-v0.1.3-00000x` index.  Would you mind attaching the logs from opni-controller-manager again?

**Comment by dbason** [comment]
Ah it looks like it's running into an issue with the RBAC that has recently been fixed as well. If you re-run
```
kubectl  apply -f https://raw.githubusercontent.com/rancher/opni/main/deploy/manifests/01_rbac.yaml
```

It should resolve that problem

**Comment by barryboubakar** [comment]
Hello Dan, 

Indeed the new rbac fixed the issue and it working as expected (we have index logs-v0.1.3-00000x and more in kibana)
however we encounter a weird behaviour, when we connect for the first time we see the "Opni Logs Dashboard" but when the session timeout the dashboard has disapeared.
We made a copy of the dashboard and even the copy is missing.
 
Thank you for your help.

**Comment by dbason** [comment]
Normally that is because the tenant has changed from global to the local admin tenant in dashboards.  If you click the user drop down in the top right there should be an option to switch tenants.  If you switch back to the global tenant the dashboard should who up in the UI again.

**Comment by dbason** [comment]
@barryboubakar I'm going to close out this issue, but if you have any further problems please raise a new one.

**Comment by barryboubakar** [comment]
Hi @dbason , sorry for the delayed reply. Thank you for your help on this issue. Now everything is OK from my side.
