### ISSUE TITLE
MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found

### ISSUE THREAD

**Issue by 24237805** [rancher/opni#175]
when I execute command, see below error, want to know where is the "webhook-server-cert"?
kubectl  apply -f https://raw.githubusercontent.com/rancher/opni/main/deploy/manifests/10_operator.yaml

MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found

**Comment by dbason** [comment]
The cert secret should be created by Cert Manager, and this error should resolve after a short wait.  Is cert-manager installed in your k8s environment?

You can install it with a command like the following:
```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
```

**Comment by 24237805** [comment]
@dbason it works for me now, thanks a lot
