### ISSUE TITLE
customer kubernetes cluster how to use LogAdapter

### ISSUE THREAD

**Issue by 24237805** [rancher/opni#178]
Currently I setup the kubernetes cluster by myself(kubeadm init) without using rke/rke2/aks/eks , so I'm not sure how to use LogAdapter, as the provide should be one of the rke/rke2/aks/eks, could you give some suggestions

**Comment by 24237805** [comment]
I already set it to generic, but see errors: The LogAdapter "lga" is invalid: spec.provider: Unsupported value: "generic": supported values: "aks", "eks", "gke", "k3s", "rke", "rke2"

**Comment by kralicky** [comment]
The generic provider was only added in v0.3.0, so check to make sure you are using the latest version.

**Comment by 24237805** [comment]
I just install it from this url https://raw.githubusercontent.com/rancher/opni/main/deploy/manifests/20_cluster.yaml, and I saw its version is v0.3.0, any wrong from my side?

**Comment by kralicky** [comment]
You may have an older version of the CustomResourceDefinitions from a previous installation. Try re-applying those and you should then have the generic provider available to use.

**Comment by 24237805** [comment]
thanks @kralicky , I checked this URL, https://raw.githubusercontent.com/rancher/opni/main/deploy/manifests/00_crds.yaml, and found provider is missing "generic", I just add it by myself, maybe need update this.

**Comment by kralicky** [comment]
Good catch, thanks! I'll update it now.
