### ISSUE TITLE
Anomaly detection using Drain/Nulog

### ISSUE THREAD

**Issue by Zakaria-laktati** [rancher/opni#184]
Hello,

I want to thank you for this nice job.

we deployed OPNI on a private RKE1 cluster and connected it to a data stream from another RKE1 cluster. Then we triggered an incident trying to deploy a bad hello world with 50 failed pods, except that all generated logs have been detected as normal.

I'm trying to find out if this is normal or if we need to re-train the model... And what exactly is the model used to classify logs as normal, sucpicious or anomaly?

thank you in advance

**Comment by sanjay920** [comment]
hey @Zakaria-laktati 
We have pretrained model for control plane logs.
If there is a gpu attached to your cluster, a deep learning model will be trained in your cluster and this model would be used for classifying workload logs. Do you have a GPU attached in your setup?
can you share more details on the `bad hello world`? Are the generated logs you are looking at control plane or workload logs?

**Comment by Zakaria-laktati** [comment]
Hey @sanjay920 

the generated logs are control plane logs. The hello world that we tried to deploy in order to test the model is composed of 50 pods stuck in pending status and here is the exact error message :
**0/4 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/controlplane: true}, that the pod didn't tolerate, 3 node(s) didn't match Pod's node affinity.**

**Comment by dbason** [comment]
@Zakaria-laktati thanks for that.  Normally we would expect to see logs about this come from kube-scheduler.  Scheduler issues can be a little tricky to classify correctly, and depending on the verbosity settings sometimes aren't even emitted by the logging.

I'll dig into this some more and get back to you, could you let me know what version of RKE you are using, what version of kubernetes, and whether there are any custom verbosity settings?

**Comment by Zakaria-laktati** [comment]
@dbason thanks for these informations. In the meantime here is the requested information :

Version of Kubernetes : 1.20.10
version of RKE : 1.3.0

**Comment by sanjay920** [comment]
Opni v0.4 no longer inferences on workload logs. This feature will be reintroduced in the future.
