### ISSUE TITLE
OpenSearch OIDC Support

### ISSUE THREAD

**Issue by oliverbaehler** [rancher/opni#1850]
Should Opni directly integrate OpenSearch with OpenID (as done with Grafana)? Since it would be supported (https://opensearch.org/docs/latest/security/authentication-backends/openid-connect/). If i am getting right, currently only the local administrator is created out of the box?

**Comment by kralicky** [comment]
Hey @oliverbaehler, we are actually working on this right now: https://github.com/rancher/opni/pull/1799 :slightly_smiling_face: 
This will be available in the 1.0 release.

**Comment by oliverbaehler** [comment]
@kralicky oh thanks, did not spot that one. Hype for the v1 then! :)
