### ISSUE TITLE
Root Cause Analysis investigation & experimentation

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#290]
investigate papers and experiment implementations of Root Cause Analysis from logs and traces.

**Comment by tybalex** [comment]
RCA based on system and service level metrics: https://hal.inria.fr/hal-02441640/document#:~:text=MicroRCA%20infers%20root%20causes%20in,propagation%20across%20services%20and%20machines 
this is something we can try out and potential adapt to immediately

**Comment by tybalex** [comment]
another interesting paper: https://github.com/tybalex/dycause_rca

**Comment by tybalex** [comment]
A helpful survey: https://arxiv.org/pdf/2105.12378.pdf

**Comment by tybalex** [comment]
a summarize of RCA papers: https://github.com/dreamhomes/RCAPapers

**Comment by tybalex** [comment]
Many interesting methods assumes service mesh installed in system, however we can't. We will focus on running the experiments of those papers that uses traces. close issue.
