### ISSUE TITLE
Introduce log template aggregation for Opni log anomaly detection

### ISSUE THREAD

**Issue by AmartC** [rancher/opni#304]
For log template aggregation, the DRAIN, inferencing and Opensearch Updating services will be impacted.

A caching optimization is to be introduced to the DRAIN service where any log messages that are not currently part of the cache will be sent to the inferencing service. Once that service makes its prediction, the result is sent back to the DRAIN service where it will update its cache for that log message and the anomaly level. The DRAIN service will now be the sole microservice in log anomaly detection to send over results to the Opensearch Updating Service.

**Comment by tybalex** [comment]
rollover to sprint 4

**Comment by AmartC** [comment]
Rollover to Sprint 5.

**Comment by AmartC** [comment]
Log template aggregation has been implemented and has been tested out and the functionality works as expected. An optimization for persistence is being implemented now.

**Comment by AmartC** [comment]
PR has been submitted for DRAIN service and Inferencing service.

**Comment by AmartC** [comment]
Currently addressing feedback on PR.

**Comment by AmartC** [comment]
Approach taken is to have two TemplateMiners. One for the dedicated pre-trained model which won't be modified at all. If the log matches with that template, then fetch the anomaly level and template, otherwise, check with the active DRAIN model being built.
