### ISSUE TITLE
K8s Events UI

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#309]

**Comment by dbason** [comment]
![events.png](https://zube.io/files/rancher/1f57a5049185066c9830bfa9a99e2a9e-events.png)
Add annotations similar to this to the Anomaly timeline.  The vertical lines are probably too noisy so maybe we can skip those.

Custom search for events is added as part of rancher/opni#335, but should we have custom UI for this?

Should potentially add events to the sparklines view.  I think we can include some more event elements to the Rancher specific part of the UI.
