### ISSUE TITLE
Kick off data collection for Longhorn pre-train model

### ISSUE THREAD

**Issue by tybalex** [rancher/opni#368]
In addition to the pre-trained models for control plane and Rancher logs, the next pre-trained model will be for Rancher longhorn logs.

**Comment by AmartC** [comment]
The first steps involved are to setup Rancher longhorn on a downstream cluster and ship those logs over to a central Opni cluster to observe what the logs look like as well as to define criteria for identifying Longhorn logs.

**Comment by AmartC** [comment]
Running Rancher longhorn v1.3.0 on a downstream cluster, shipped over logs to a central Opni cluster. From there, have collected over 11000 log messages from the longhorn-system namespace.

**Comment by AmartC** [comment]
Longhorn logs have been collected and are now being annotated and processed before the model is to be trained.
