### ISSUE TITLE
Each LogCluster/DRAIN template needs to keep track of an example log

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#449]
Goal is for the templates page in the Opni UI to keep track of an example log for every template in the DRAIN model.

Example template:
```
<num><path> <num> : <num> : <num> info starting cluster controllers for <token_with_digit>
```
Example log stored within DRAIN LogCluster/template:
```
2022/04/19 14:20:17 [INFO] Starting cluster controllers for c-6qcx2![image.png]
```

The example log should be updated as log counts are updated to their respective templates.

**Comment by AmartC** [comment]
PR is now in review.
