### ISSUE TITLE
null blocks in `bucket-index.json.gz` for cortex ruler on startup

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#502]
e2e tests for opni-agent fail 100% of the time.
There are several symptoms i've observed besides the 503s when the agent tries to write metrics : 

-  a null block in `bucket-index.json.gz` for cortex rules:
- cortex compactor crash
- rule sync pending state for agent

**Comment by alexandreLamarre** [comment]
This happens at startup, and there is no `bucket-index.json.gz` file existing after startup, it must be getting written to later

**Comment by alexandreLamarre** [comment]
Content of the rules `bucket-index.json` file is : 
```
version	1
blocks	null
block_deletion_marks	[]
updated_at	1660745155
```

**Comment by alexandreLamarre** [comment]
2022-08-17T16:10:42.026Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:42.032Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:42.035Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:43.027Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:43.037Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:43.040Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:44.024Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:44.032Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:44.036Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:45.027Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:45.038Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:45.044Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:46.022Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:46.028Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:46.031Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:47.023Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:47.028Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:47.032Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:48.026Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:48.036Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:48.040Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:49.022Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:49.028Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:49.032Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:50.027Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:50.037Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:50.042Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:51.026Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:51.035Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2     2022-08-17T16:10:51.039Z ERROR test.env.bench failed to send batch {"agent": "ba3cef75-82a2-42e3-9dcd-35ed7c27e464", "error": "server returned HTTP status 503 Service Unavailable: "}
12:10PM INFO  actions.e2e.test._exec | #54 960.2   << End Captured GinkgoWriter Output
12:10PM INFO  actions.e2e.test._exec | #54 960.2
12:10PM INFO  actions.e2e.test._exec | #54 960.2   Timed out after 10.001s.
12:10PM INFO  actions.e2e.test._exec | #54 960.2   Expected
12:10PM INFO  actions.e2e.test._exec | #54 960.2       <string>: Rule Sync Pending
12:10PM INFO  actions.e2e.test._exec | #54 960.2   to equal
12:10PM INFO  actions.e2e.test._exec | #54 960.2       <string>: ok

**Comment by kralicky** [comment]
Possibly caused by #517
