### ISSUE TITLE
Fix/optimize plugin patching memory usage

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#682]
Plugin patching can use a lot of memory in some cases (several GB). Need to investigate and optimize memory usage.

**Comment by alexandreLamarre** [comment]
![image.png](https://zube.io/files/rancher/1de1867e498f00e6ed511caf57e51b8c-image.png)

**Comment by alexandreLamarre** [comment]
I did some preliminary profiling, the io.ReadAll and it seems like that is the overwhelming cause of the memory usage. 

Couple of optimizations: 
- streaming IO for patch application / generation
- minor reordering
- using bytebuffer pools in our iterations over plugins to mark big allocations as ready to delete

**Comment by alexandreLamarre** [comment]
Old performance estimate (4 plugins = 25MB *2):
![old perf estimate](https://user-images.githubusercontent.com/56211853/198110758-9f858084-761b-4626-9b26-0170330d15f1.png)

New performance estimate (5 plugins = 30MB *2):
- re-arranging some file operations
- stream buffered io
![new perf estimate](https://user-images.githubusercontent.com/56211853/198110837-17d87a65-65a3-4cc0-8a87-e47bdebabef5.png)
