### ISSUE TITLE
name set for "cluster name" in add cluster doesn't appear

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#705]
A user can set a "Cluster Name" when adding a new downstream cluster, but the name doesn't show up in the clusters page - the cluster ID does.
Expected behavior is that the name set in creation of the downstream cluster appears in the clusters list

![image.png](https://zube.io/files/rancher/7d0901f30d0f02ff59652e1d4d8d24e7-image.png)
![image.png](https://zube.io/files/rancher/92fc7a7de080f5d92d529fcfd8d0a00d-image.png)

**Comment by kralicky** [comment]
@codyrancher  When updating the cluster labels upon clicking the Finish button, you have to first fetch the current labels and then the name label to it. You will get an error if any immutable labels added to the cluster on creation time (in this case `opni.io/agent-version`) are not present in the edit request.
