### ISSUE TITLE
Compactor data_dir is incorrect (All-in-one + FS does not function)

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#757]
The compactor is using the default data_dir of `/data`, which conflicts with other services' data storage when using all-in-one mode.

**Comment by alexandreLamarre** [comment]
Will look at fixing the alertmanager `data_dir` as well to prevent any clashes there

**Comment by alexandreLamarre** [comment]
compactor data_dir doesn't appear to be the culprit creating recursive empty `bucket-index.json.gz` null marker blocks in every globbed directory `/data/*/<tenant_id>/*`
