### ISSUE TITLE
Enable both ingest plugin in a future release

### ISSUE THREAD

**Issue by tybalex** [rancher/opni#758]
Now we have 2 plugins:
the Logging plugin: normalize the `time` and `log` field from incoming logs, which is needed for the dashboard. It also detects Json objects in the logs.
the AIOps plugin: do some extra preprocessing that needed for the AI services + sending logs to Nats.

Ideally, if the Logging backend is enabled but AIOps not enabled , only the Logging plugin should be installed: and if AIOps got enabled, both plugin should be installed in the pipeline.

**Comment by dbason** [comment]
Initial pass we will just enable both plugins when logging is enabled.  If AIOps isn't enabled there should be no queue groups so the NATs messages will just get blackholed.
