### ISSUE TITLE
OpniOpensearch object created by logging plugin has no owner references

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#764]
The OpniOpensearch created by the logging plugin isn't being cleaned up when uninstalling opni, it should be parented to the opni-agent statefulset similar to metrics plugin here: https://github.com/rancher/opni/blob/main/plugins/metrics/pkg/agent/drivers/external_operator.go#L311-L339

**Comment by dbason** [comment]
OpniOpensearch is the top level resource that controls installing or uninstalling the logging backend so definitely shouldn't be parented by the agent statefulset.
