### ISSUE TITLE
No metrics in Grafana for Kubernetes cluster

### ISSUE THREAD

**Issue by Kapsztajn** [rancher/opni#840]
Hello,
I'm currently testing OPNI to change Thanos + Prometheus. I installed it in my cluster and enabled monitoring on it and I can't see any data in Grafana.
![image](https://user-images.githubusercontent.com/23492161/202478581-d2b3ca7f-fb4f-4353-82c3-db2af7dd0ee5.png)
![image](https://user-images.githubusercontent.com/23492161/202478663-12cbec82-2cca-4bc7-836f-2d681e4470cf.png)

I can see metrics only in dashboard opni-gateway. Do I need to configure something more? I'm not an expert in Grafana stack.
![image](https://user-images.githubusercontent.com/23492161/202479129-eed48594-60c0-4991-969a-17e67aeb9891.png)

**Comment by kralicky** [comment]
Hi @Kapsztajn! What version of Opni are you using?

**Comment by kralicky** [comment]
Try updating Opni to 0.6.3 (latest release), it includes fixes for Grafana dashboards. Let me know if that works!

**Comment by Kapsztajn** [comment]
Yes, it works perfectly fine now! Thank you so much for your help, time, and for this amazing tool.
